ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc  = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.rebalance_trap]
path = "out/RebalanceTrap.sol/RebalanceTrap.json"
response_contract = "0x3dAF8d70Ef1D029B96E1ae7311E5EF724B6F0C83"
response_function = "handle(bytes)"                     
cooldown_period_blocks = 12
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 1
private_trap = true
whitelist = ["0xf05F1fA2bC6cE0a8905494892A961536460d4c95"]
address = "0x3fB8B3f84c56f24CAAc810D401AD04d7feae2f59"

